version: '3.9'

services:
  regression:
    image: python:3.11.1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:usr/workspace
    command: /bin/sh -c "ls -la && pytest -sv --alluredir=allure-results"
    working_dir: /usr/workspace
    environment:
      - LOGIN=${LOGIN}
      - PASSWORD=${PASSWORD}